Add script to fix a corrupt ZSH history file

diff --git a/bin/newscript b/bin/newscript
--- a/bin/newscript
+++ b/bin/newscript
@@ -1,6 +1,6 @@
 #!/usr/bin/env ruby
 #
-#   Copyright 2016 Joe Block <jpb@unixorn.net>
+#   Copyright 2016-2020 Joe Block <jpb@unixorn.net>
 #
 #   Licensed under the Apache License, Version 2.0 (the "License");
 #   you may not use this file except in compliance with the License.
@@ -49,6 +49,20 @@ def generate_bash_script(name:)
 # Copyright #{copyright_year}, Your Name <yourname@yourdomain.com>
 
 set -o pipefail
+
+# Set up a working scratch directory
+SCRATCH_D=$(mktemp -d)
+
+if [[ ! "$SCRATCH_D" || ! -d "$SCRATCH_D" ]]; then
+  echo "Could not create temp dir"
+  exit 1
+fi
+
+cleanup() {
+  if [[ -d "$SCRATCH_D" ]]; then
+    rm -fr "$SCRATCH_D"
+  fi
+}
 
 END_BASH_SCRIPT
   write_script(name: name, source: rawScript)
